### PR TITLE
Add img that would be shown on twitter and other platforms

### PR DESCRIPTION
**Pull request by portdeveloper**
## Description

This PR adds an img to the public folder and links to it in the [[...address]] page so that when address.vision is shared on a platform, e.g. twitter, a very basic logo + text as an image will be shown just like abi.ninja.

Here is the img i """"designed"""" on Word
ss 2023-11-08 110522

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Comment by portdeveloper** [comment]
So, I looked at abi.ninja's repo and did everything exactly the same but I cannot get the image to show up on twitter but  the card validator detects it.
This is https://address-vision-port-git-feat-add-thumbnail-buidlguidldao.vercel.app/
image
And this is abi.ninja
image

**Comment by portdeveloper** [comment]
Now even abi.ninja does not work lol. Let's keep this PR open and ask someone who has dealt with this before i guess.

**Comment by carletex** [comment]
Hey @portdeveloper just here to say that I love your word art.

image

---

Regarding the URL unfurl. Yeah, it's always a pain (specially twitter). Absolutes URL are always needed for it to work.

I'd say: take a look at the MetaHeader component on SE-2: https://github.com/scaffold-eth/scaffold-eth-2/blob/main/packages/nextjs/components/MetaHeader.tsx.

Builds deployed with the latest versions of SE-2 seem to keep working on twitter / telegram. (e.g. https://speedrun-chainlink.vercel.app/)

Also, telegram takes some time to refresh (check https://stackoverflow.com/questions/35268940/how-to-force-telegram-to-update-the-link-preview for solutions).

**Comment by portdeveloper** [comment]
Thanks @carletex ! 

It was just me missing the obvious again :D After some trial and error, it finally worked!

**Comment by carletex** [comment]
Looking good!!

**Pull request merged**
